### ISSUE TITLE
Issues with k index

### ISSUE THREAD

**Issue by saadtony** [saadgroup/PyModPDE#2]
I Tried playing around with the indices:
DE1 = DifferentialEquation(dependentVar='u',independentVars=['x'], indices=[k], timeIndex=n)
This throws an error

**Comment by mk-95** [comment]
`from src.MOIRA import DifferentialEquation, i, k, n`
`k` is an index, so either you can import it from `src.MOIRA` 
or locally define your own sympy symbol and use it in `indices`
`k = symbols('k')`
